version: "3.7"

x-defaults:
  network: &network
    networks:
      - net

  selenium-services: &selenium-svc
    environment:
      # Required to avoid container startup hanging sometimes in
      # some environments
      JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
    ports:
      - "4444:4444"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    <<: *network

services:
  php:
    # Custom PHP Image - see /images/Readme.md
    image: dhluther/php:7.4-debug
    volumes:
      - ./src:/var/www/html
    <<: *network

  composer:
    image: composer:latest
    command: ['bash','-c',"sleep infinity"]
    volumes:
      - ./src:/var/www/html
    <<: *network

  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    configs:
      - source: nginx-conf
        target: /etc/nginx/conf.d/default.conf
      - source: nginx-base-conf
        target: /etc/nginx/nginx.conf
    <<: *network

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
    volumes:
      - ./data:/var/lib/mysql
    secrets:
      - db_pwd
    <<: *network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8081:80
    <<: *network
    volumes:
      - /sessions

  #Used for Acceptance Tests for Firefox
  firefox:
    image: selenium/standalone-firefox-debug:2.53.0
    <<: *selenium-svc

  #Used for Acceptance Tests for Chrome
  chrome:
    image: selenium/standalone-chrome-debug
    <<: *selenium-svc
    ports:
      - "4443:4444"

networks:
  net:

secrets:
  db_pwd:
    file: ./root_db_password.txt

configs:
  nginx-conf:
    file: ./nginx/default.conf
  nginx-base-conf:
    file: ./nginx/nginx.conf