version: "3.7"

services:
  php:
    # https://hub.docker.com/_/php
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
    secrets:
      - db_pwd

secrets:
  db_pwd:
    file: ./root_db_password.txt