version: "3.7"

services:
  php:
    # Custom PHP Image - see /images/Readme.md
    image: dhluther/php:7.4-debug
    volumes:
      - ./src:/var/www/html

  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    configs:
      - source: nginx-conf
        target: /etc/nginx/conf.d/default.conf
      - source: nginx-base-conf
        target: /etc/nginx/nginx.conf

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
    volumes:
      - ./data:/var/lib/mysql
    secrets:
      - db_pwd

secrets:
  db_pwd:
    file: ./root_db_password.txt

configs:
  nginx-conf:
    file: ./nginx/default.conf
  nginx-base-conf:
    file: ./nginx/nginx.conf