ARG PHP_TARGET=7.4-apache

FROM php:$PHP_TARGET as base

RUN docker-php-ext-install -j$(nproc) mysqli pdo_mysql

FROM base as customized
ENV PHP_INI_DIR /usr/local/etc/php

COPY ./php_config/tz.ini $PHP_INI_DIR/conf.d/
COPY ./php_config/custom.ini $PHP_INI_DIR/conf.d/
COPY ./php_config/www.mysite.conf /usr/local/etc/php-fpm.d/

FROM customized as debug
RUN yes | pecl install xdebug \
	&& echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > $PHP_INI_DIR/conf.d/xdebug.ini \
	&& echo "xdebug.remote_enable=on" >> $PHP_INI_DIR/conf.d/xdebug.ini \
	&& echo "xdebug.remote_autostart=off" >> $PHP_INI_DIR/conf.d/xdebug.ini
EXPOSE 8080 80 9000 9001

RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version \
    && mkdir -p /tmp/blackfire \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
    && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get('extension_dir');")/blackfire.so \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" > $PHP_INI_DIR/conf.d/blackfire.ini \
    && rm -rf /tmp/*